# -*- coding: utf-8 -*-
"""Palmeiras_testa_jogadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVbzoPGe5UTuQww-MG_ZedfD-nhuEyif
"""

import pandas as pd
import numpy as np
from google.colab import data_table
data_table.enable_dataframe_formatter()
import warnings
warnings.filterwarnings('ignore')

from google.colab import files

"""# Importa o Arquivo de Dados obtido do Verdazzo.com"""

uploaded = files.upload() # Carrega todos os dados

file = 'verdazzo.csv'
df_jogos = pd.read_csv(file,sep=';',skipinitialspace=True)

df1 = df_jogos[['Data','Mandante','Visitante','Campeonato']]
df1.index = df1.index.set_names(['Partida'])
df1.reset_index(inplace=True)

lista_datas = df1.set_index('Partida').T.to_dict('list')

# Criando o Dicionário com a Lista de Jogos
df2 = df_jogos.iloc[: , [4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]].copy()
df2.index = df2.index.set_names(['Partida'])
df2.reset_index(inplace=True)

lista_jogos = df2.set_index('Partida').T.to_dict('list')

njogos = len(lista_jogos)

def escalacao(jogadores):
  flag = 0
  jogos=[]
  for i in range(njogos):
    if set(jogadores).issubset(lista_jogos[i]):
      flag=1
      jogos.append(i)
  if flag == 0:
    print('Nenhum jogo encontrado corresponde aos jogadores pesquisados')

  for item in jogos:
    jogo = [s.title() for s in list(lista_jogos[item]) if str(s) != 'nan']
    jogo = [x.replace('-', ' ') for x in jogo]
    print(f'Partida {item}: {lista_datas[item][0]} {lista_datas[item][1].title()} X {lista_datas[item][2].title()} ({lista_datas[item][3].title()})')
    for jogador in jogo:
      print(jogador)
    print()

  print(f'Total de Partidas: {len(jogos)}')
  print(jogadores)

escalacao(['Weverton','Gustavo Goméz','Marcos Rocha','Zé Rafael','Dudu','Rony'])

